apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessapp-client
  labels:
    tier: frontend
    type: application
spec:
  selector:
    matchLabels:
      app: chessapp-client
  replicas: 1
  template:
    metadata:
      labels:
        app: chessapp-client
    spec:
      containers:
        - name: chessapp-client
          image: shntrn/chessapp_client:latest


---
kind: Service
apiVersion: v1
metadata:
  name: chessapp-client
spec:
  selector:
    app: chessapp-client
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP