apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessapp-server
  labels:
    tier: backend
    type: server
spec:
  selector:
    matchLabels:
      app: chessapp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: chessapp-server
    spec:
      containers:
        - name: chessapp-server
          image: shntrn/chessapp_server:latest

---
kind: Service
apiVersion: v1
metadata:
  name: chessapp-server
spec:
  selector:
    app: chessapp-server
  ports:
    - protocol: TCP
      port: 8081
  type: ClusterIP