version: '3.3'
services:
  server:
    container_name: chessApp_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
     - '8081:8081'
    links:
     - mongo
    environment:
     DB_URL: mongodb://mongo:27017/chessMEAN
  app:
    container_name: chessApp_client
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '8080:80'
    links:
      - mongo
      - server
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

