apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    tier: backend
    type: database
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
        - name: mongo-volume
          hostPath:
            path: /home/shntrn/mongo-volume
            type: DirectoryOrCreate
---
kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
  type: ClusterIP
